config/routes.rb
Rails.application.routes.draw do
  get 'todos', to: 'todos#index'
  get 'todos/new'
  post 'todos', to: 'todos#create'

  get 'todos/list'
  get 'todos/:id', to: 'todos#show', as: 'todo'
  get 'todos/:id/edit', to: 'todos#edit', as: 'edit'
  patch 'todos/:id', to: 'todos#update'
  delete 'todos/:id', to: 'todos#destroy'
  get 'todos/:id/complete', to: 'todos#complete', as: 'completed'
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
  validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    @todos = Todo.all
  end

  def new
    @todo = Todo.new
  end

  def create
    @todo = Todo.new(todo_params)
    @todo.save
    redirect_to todos_path
  end

  def show
    @todo = Todo.find(params[:id])
  end

  def edit
    @todo = Todo.find(params[:id])
  end

  def update
    @todo = Todo.find(params[:id])
    @todo.update(todo_params)
    redirect_to todos_path
  end

  def destroy
    @todo = Todo.find(params[:id])
    @todo.destroy
    redirect_to todos_path
  end

  def complete
    @todo = Todo.find(params[:id])
    @todo.completed = true
    @todo.save
    redirect_to todos_path
  end

  def list
    @todos = Todo.all
  end


  private
  def todo_params
    params.require(:todo).permit(:description, :completed)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script   src="https://code.jquery.com/jquery-1.12.4.min.js"   integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ="   crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">To Do List App</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Index', todos_path %></li>
        <li><%= link_to 'List', todos_list_path %></li>
        <li><%= link_to 'Crear nuevo', todos_new_path %></li>
      </ul>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
    <div class="container">
        <%= yield %>
    </div>
  </body>
</html>

app/views/todos/_formulario.html.erb
<div class="container">
  <h1>ToDo List</h1>
    <div class="mi_form">
      <%= form_with(model: @todo, local: true) do |form| %>
        <% if @todo.errors.any? %>
          <div id="error_explanation">
            <h2>
              <%= pluralize(@todo.errors.count, "error") %>
              error al crear:
            </h2>
            <ul>
              <% @todo.errors.full_massages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        
        <% end %>

        <div class="form-group">
          <fieldset>
            <%= form.label :description %>
            <%= form.text_field :description, class: "form-control", placeholder: "Ingrese descripción" %>
          </fieldset>
        </div>

    <div class="form-group">
          <fieldset>
            <%= form.label :completed %>
            <%= form.check_box :completed, class: "form-control" %>
          </fieldset>
        </div>

        <div class="form-group">
          <fieldset>
            <%= form.submit 'Guardar'%>
          </fieldset>
        </div>
      <% end %>
    </div>
   </div>
</div>

app/views/todos/edit.html.erb
<%= render 'todos/formulario' %>

app/views/todos/index.html.erb
<div class="container">
  <h1>ToDo List</h1>
  <%= link_to 'Crear ToDo', todos_new_path %>
    <% @todos.each do |todo| %>
      <div class="well" style="background: green">
        <h1><%= todo.description %></h1>
         <p><%= todo.completed ? 'Completado' : 'No Completado' %></p>
      </div>
      <%= link_to 'show', todo_path(todo.id) %>
      <%= link_to 'edit', edit_path(todo.id) %>
      <%= link_to 'destroy', todo, method: :delete %>
      <%= link_to 'completed', completed_path(todo.id) %>
   <% end %>
</div>

app/views/todos/list.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <h1>No Completados</h1>
      <% @todos.each do |todo| %>
        <% if !todo.completed? %>
          <p><%= todo.description %></p>
          <% end %>
        <% end %>
    </div>

    <div class="col-md-6">
      <h1> Completados</h1>
      <% @todos.each do |todo| %>
        <% if todo.completed? %>
          <p><%= todo.description %></p>
          <% end %>
        <% end %>
    </div>
  </div>
</div>

app/views/todos/new.html.erb
<%= render 'todos/formulario' %>

app/views/todos/show.html.erb
<div class="container">
  <h1>ToDo List</h1>
      <h1><%= @todo.description %></h1>
       <p><%= @todo.completed ? 'Completado' : 'No Completado' %></p>
    </div>
</div>